#!/usr/bin/python3

def pedirNumeroEntero():
def pedirLetra();

    correcto=False
    num=0
    while(not correcto):
        try:
            num = int(input("No introduciste un numero entero"))
            correcto=True
        except ValueError:
            print('Error, introduce un numero entero')

    return num

salir = False
opcion = 0

while not salir:
    print ("a) Ingrese el alfabeto")
    print ("Seleccione como quiere ingresar los datos:")
    print ("1. Opcion 1: Ingresar datos uno por uno")
    print ("2. Opcion 2: Ingresar rango de datos")
    print ("3. Opcion 3: Salir")
    print ("Elige una opcion")

    opcion = pedirNumeroEntero()
    if opcion == 1:
        cadena1=input("Introduce el alfabeto 1:")
        print ("El alfabeto 1 es:\n", cadena1)
        cadena2=input("Introduce el alfabeto 2:")
        print ("b)Leer el alfabeto 2 es:\n",cadena2)
    elif opcion == 2:
        n=input("Ingresa el inicio de tu rango")
        m=input("Ingresa el final de tu rango")
        print ("Tu rango es:\n ", n, m)


    elif opcion == 3:
        salir = True
    else:
        print ("Introduce un numero entre 1 y 3")
